baseURL = "https://kesselova.sk/"
languageCode = "en-us"
theme = "journal"
title = "JUDr. KatarÃ­na KesselovÃ¡"

[params]
description = "Raz tu z tohto bude blog."
tagline = "Raz tu z tohto bude blog. ğŸ¤·â€â™€ï¸"
